[project]
name = "flowlined-zeb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "concurrent-openai>=1.2.2",
    "fastapi>=0.68.0",
    "gunicorn>=20.1.0",
    "httpx>=0.24.0",
    "loguru>=0.7.3",
    "openai>=1.0.0",
    "pydantic>=2.0.0",
    "pytest-asyncio>=0.26.0",
    "pytest>=7.0.0",
    "python-dotenv>=0.19.0",
    "redis>=6.0.0",
    "uvicorn>=0.15.0",
    "numpy>=2.2.5",
    "pytest-mock>=3.14.0",
]
