name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "~/.cargo/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          uv sync
          # Ensure python-dotenv is installed if not in requirements.txt/pyproject.toml
          uv pip install pytest ruff python-dotenv
      - name: Create .env file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
      - name: Lint
        run: |
          uv run ruff check --fix
          uv run ruff check --unsafe-fixes
      - name: Test
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          # The load_dotenv() in your config.py should now pick up the key from .env
          uv run pytest
      - name: Build Docker image
        run: docker build -t flowlined-zeb .
